//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEWebApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;
    using System.Web;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.ProImage = "~/Content/images/default_img.jfif";
        }

        [Display(Name ="SDT")]   
        public string CusPhone { get; set; }

        [Display(Name = "Password")]
        public string CusPassword { get; set; }

        [Display(Name ="UserName")]
        public string CusName { get; set; }

        [Display(Name ="Email")]
        public string CusEmail { get; set; }

        [Display(Name ="Ma don hang")]
        public int OrderID { get; set; }

        [Display(Name = "Ngay dat hang")]
        public Nullable<System.DateTime> OrderDate { get; set; }

        [Display(Name ="Tong tien")]
        public Nullable<double> TotalValue { get; set; }

        [Display(Name ="Anh")]
        public string ProImage { get; set; }

        [Display(Name =" Ten MH")]
        public string ProName { get; set; }

        [Display(Name ="NCC")]
        public string SupName { get; set; }

        [Display(Name ="Don gia")]
        public Nullable<double> UnitPrice { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
